{{- if .Values.customFeedsServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gvm.fullname" . }}-feeds-server
  labels:
  {{- $_ := set . "applicationNameSuffix" "feeds-server" }}
  {{- include "gvm.labels" . | nindent 4 }}
  {{- $_ := set . "applicationNameSuffix" "" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gvm.name" . }}-feeds-server
      app.kubernetes.io/instance: {{ include "gvm.instance" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gvm.name" . }}-feeds-server
        app.kubernetes.io/instance: {{ include "gvm.instance" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ tpl .Values.customFeedsServer.image.registry . }}/{{ tpl .Values.customFeedsServer.image.repository . }}:{{ tpl .Values.customFeedsServer.image.tag . }}"
          imagePullPolicy: {{ tpl .Values.customFeedsServer.image.pullPolicy . }}
          ports:
            - name: rsync
              containerPort: {{ .Values.customFeedsServer.service.containerPort }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: rsync
          readinessProbe:
            tcpSocket:
              port: rsync
          resources:
            {{- toYaml .Values.customFeedsServer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
